services:
  klopf-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  klopf-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:8080"
    depends_on:
      - klopf-backend
    restart: unless-stopped
